name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Google Cloud ke sath Auth
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 2. Google Cloud SDK setup
      - uses: google-github-actions/setup-gcloud@v1

      # 3. Backend deploy
      - name: Deploy Backend
        run: |
          gcloud run deploy codecollab-backend \
          --source ./backend \
          --region asia-south1 \
          --allow-unauthenticated \
          --set-env-vars MONGO_URI=${{ secrets.MONGO_URI }},REDIS_URL=${{ secrets.REDIS_URL }}

      # 4. Sync Service deploy
      - name: Deploy Sync Service
        run: |
          gcloud run deploy codecollab-sync \
          --source ./sync-service \
          --region asia-south1 \
          --allow-unauthenticated
